// swift-tools-version: 6.3

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "Example",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Example",
            targets: ["AppModule"],
            bundleIdentifier: "27209858-C0B7-4D58-B12F-90B8092A1C8C",
            displayVersion: "1.0",
            bundleVersion: "1",
            supportedDeviceFamilies: [
                .pad,
                .phone,
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad])),
            ]
        )
    ],
    dependencies: [
        .package(name: "Licenses", path: "../"),
        .package(url: "https://github.com/apple/swift-algorithms.git", "1.2.1"..<"2.0.0"),
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Algorithms", package: "swift-algorithms")
            ],
            path: ".",
            plugins: [
                .plugin(name: "LicensesPlugin", package: "Licenses")
            ],
        )
    ]
)
